apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-alloy-scraper
  labels:
    app: alloy-scraper
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy-scraper
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: alloy-scraper
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      containers:
        - name: alloy
          image: docker.io/grafana/alloy:v1.10.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - /etc/alloy/config.alloy
          ports:
            - containerPort: 12345
              name: http-metrics
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alloy
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            # We pass the Cluster Name just in case you need it for debugging inside the pod
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mychart.fullname" . }}-alloy-config
