{{- include "requiredValues" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-log-cleaner
  namespace: {{ .Release.Namespace }}   
  labels:
    app: {{ .Release.Name }}-log-cleaner
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-log-cleaner
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-log-cleaner
    spec:
      # Master Node  Tolerations
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: cleaner
        image: busybox:latest  
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          # SETTING: Check logs every 5 Minutes (120 seconds)
          CLEAN_INTERVAL=120
          
          echo "🧹 Log Cleaner started on $(hostname)..."
          
          while true; do
            echo "Searching for kube-bench logs to clean..."
            
            # Find and empty the log files without deleting them
            find /var/log/containers -name "*kube-bench*.log" -type f -exec truncate -s 0 {} \;
            
            echo "✅ Logs cleaned. Sleeping for ${CLEAN_INTERVAL}s..."
            sleep $CLEAN_INTERVAL;
          done
          
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      restartPolicy: Always
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
