apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-event-exporter-cr
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-event-exporter-crb
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-event-exporter-cr
subjects:
  - kind: ServiceAccount
    # This name MUST match the one in your error log: kubesage-release-kubesage-agent
    name: {{ .Release.Name }}-kubesage-agent
    namespace: {{ .Release.Namespace }}
