apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-event-exporter-config
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    clusterName: "{{ .Values.clusterName }}"
    logFormat: json
    logLevel: debug
    maxEventAgeSeconds: 60

    ## Webhook Receiver Configuration
    receivers:
      - name: webhook-receiver
        webhook:
          endpoint: "https://{{ .Values.endpoint }}:8008/api/remediation/v1/webhook/incident"
          tls:
            insecureSkipVerify: true
          headers:
            X-Cluster-Name: "{{ .Values.clusterName }}"
            X-Agent-ID: "{{ .Values.agentId }}"
            X-API-Key: "{{ .Values.apiKey }}"
          layout:
            eventType: kubernetes-event
            metadata:
              creationTimestamp: "{{ "{{" }} .CreationTimestamp {{ "}}" }}"
              name: "{{ "{{" }} .Name {{ "}}" }}"
              namespace: "{{ "{{" }} .InvolvedObject.Namespace {{ "}}" }}"
              resource: "{{ "{{" }} .ResourceVersion {{ "}}" }}"
              uid: "{{ "{{" }} .UID {{ "}}" }}"
            reason: "{{ "{{" }} .Reason {{ "}}" }}"
            message: "{{ "{{" }} .Message {{ "}}" }}"
            type: "{{ "{{" }} .Type {{ "}}" }}"
            clusterName: "{{ "{{" }} .ClusterName {{ "}}" }}"
            source:
              component: "{{ "{{" }} .Source.Component {{ "}}" }}"
              host: "{{ "{{" }} .Source.Host {{ "}}" }}"
            firstTimestamp: "{{ "{{" }} .FirstTimestamp {{ "}}" }}"
            lastTimestamp: "{{ "{{" }} .LastTimestamp {{ "}}" }}"
            involvedObject:
              kind: "{{ "{{" }} .InvolvedObject.Kind {{ "}}" }}"
              name: "{{ "{{" }} .InvolvedObject.Name {{ "}}" }}"
              namespace: "{{ "{{" }} .InvolvedObject.Namespace {{ "}}" }}"
              apiVersion: "{{ "{{" }} .InvolvedObject.APIVersion {{ "}}" }}"
              resourceVersion: "{{ "{{" }} .InvolvedObject.ResourceVersion {{ "}}" }}"
              uid: "{{ "{{" }} .InvolvedObject.UID {{ "}}" }}"
              labels: "{{ "{{" }} .InvolvedObject.Labels | toJson {{ "}}" }}"
              annotations: "{{ "{{" }} .InvolvedObject.Annotations | toJson {{ "}}" }}"

    ## Routing Configuration
    route:
      routes:
        # Single route with drop rules and match rule
        - drop:
          # Drop events from the "kubesage-agent" namespace
          - namespace: kubesage-agent
          # Drop all Normal type events (only send Warnings)
          - type: Normal
          match:
          # Send Warning events for Pods, Services, Deployments, ReplicaSets
          - type: Warning
            involvedObject:
              kind: Pod|Service|Deployment|ReplicaSet
            receiver: webhook-receiver
