apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-trivy-operator
  labels:
    app: trivy-operator
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: trivy-operator
    {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 80
      targetPort: 8080
      protocol: TCP
